# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'downtube.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

#할것
'''
-MP3/MP4 다운 기능
-화질 선택 기능
'''

from PyQt5 import QtCore, QtGui, QtWidgets
from pytube import YouTube

DOWNLOAD_FOLDER = ".\\Downloads\\"

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(441, 269)
        MainWindow.setMinimumSize(QtCore.QSize(441, 269))
        MainWindow.setMaximumSize(QtCore.QSize(441, 269))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Link = QtWidgets.QLineEdit(self.centralwidget)
        self.Link.setGeometry(QtCore.QRect(11, 69, 421, 41))
        self.Link.setObjectName("Link")
        self.Download = QtWidgets.QPushButton(self.centralwidget)
        self.Download.setGeometry(QtCore.QRect(170, 210, 93, 28))
        self.Download.setObjectName("Download")
        self.Select = QtWidgets.QComboBox(self.centralwidget)
        self.Select.setGeometry(QtCore.QRect(110, 170, 221, 21))
        self.Select.setObjectName("Select")
        self.Select.addItem("")
        self.Select.addItem("")
        self.Select.addItem("")
        self.Title = QtWidgets.QLabel(self.centralwidget)
        self.Title.setGeometry(QtCore.QRect(20, 10, 401, 51))
        font = QtGui.QFont()
        font.setFamily("세방고딕 OTF Regular")
        font.setPointSize(20)
        self.Title.setFont(font)
        self.Title.setObjectName("Title")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 441, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.Download.clicked.connect(self.download) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.Link, self.Select)
        MainWindow.setTabOrder(self.Select, self.Download)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "다운튜브"))
        self.Link.setPlaceholderText(_translate("MainWindow", "URL입력"))
        self.Download.setText(_translate("MainWindow", "다운로드"))
        self.Select.setItemText(0, _translate("MainWindow", "360p"))
        self.Select.setItemText(1, _translate("MainWindow", "720p"))
        self.Select.setItemText(2, _translate("MainWindow", "1080p"))
        self.Title.setText(_translate("MainWindow", "다운튜브"))
        
    def download(self):
        #여기부터 다운로드 함수
        if self.Select.currentText() == "360p":
            hwajil = 18
        if self.Select.currentText() == "720p":
            hwajil = 22
        if self.Select.currentText() == "1080p":
            hwajil = "lele"

        if hwajil == "lele":
            url = self.Link.text()
            yt = YouTube(url)
            stream = yt.streams.get_highest_resolution()
            stream.download(DOWNLOAD_FOLDER)
        else:
            url = self.Link.text()
            yt = YouTube(url)
            stream = yt.streams.get_by_itag(hwajil)
            stream.download(DOWNLOAD_FOLDER)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
